
spring:
  application:
    name: Reactive-Mongo

  data:
    mongodb:
      # uri: mongodb://<username:password@>[ip:port]/[database-name]<?options...>
      uri: mongodb://kimbs:kimbs@127.0.0.1:27017/agent
      auto-index-creation: true
      repositories:
        type: reactive

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
#    - org.springframework.data.mongodb.core.MongoTemplate: DEBUG
org:
  kimbs:
    use-mongo-replica: false